version: '3.8'

services:
  drw-dev:
    build: .
    container_name: drw-development
    volumes:
      # Mount the SSH keys for persistent access
      - ./drw-code-deploy:/root/.ssh/id_ed25519:ro
      - ./drw-code-deploy.pub:/root/.ssh/id_ed25519.pub:ro
      # Mount the repositories for live development (optional - uncomment if you want live sync)
      # - ./repos/drw-data:/app/drw-data
      # - ./repos/drwcomp2025:/app/drwcomp2025
    ports:
      - "8000:8000"  # For web applications
      - "8888:8888"  # For Jupyter notebooks
    environment:
      - PYTHONPATH=/app/drwcomp2025
    stdin_open: true
    tty: true
    command: ["/usr/local/bin/activate-env", "/bin/bash"]
    
  # Alternative service for running specific commands
  drw-run:
    build: .
    container_name: drw-runner
    volumes:
      - ./drw-code-deploy:/root/.ssh/id_ed25519:ro
      - ./drw-code-deploy.pub:/root/.ssh/id_ed25519.pub:ro
    environment:
      - PYTHONPATH=/app/drwcomp2025
    profiles:
      - run 